name: HAProxyImplementor
author: ytendx
version: 1.1.3
api-version: 1.13
main: de.ytendx.haproxy.HAProxySpigotImplementor
website: https://neoprotect.net/
description: Allows the usage of ip forwarding via the HAProxy Protocol v2/v1
commands:
  haproxyimplementor:
    description: Shows information about the plugin
    usage: /haproxyimplementor
    aliases:
      - haproxy
      - proxyimplementor
      - proxyprotocol